### ISSUE TITLE
core dump by version command

### ISSUE THREAD

**Issue by jh4xsy** [oe5hpm/openBCM#2]
I execute "v" command, then core dumped. 

    (JH4XSY)-->v
    
    Date: 25.08.2018 17:09:22l
    
    OpenBCM V9f93-dirty (Linux)
    (c) GNU GPL 1992-2013 F. Radlherr, DL8MBT et al.
    OpenBCM is maintained by Markus Baumann, DH8YMB
    https://github.com/oe5hpm/openbcm
    Compiled Aug 25 2018 17:05:13 with GCC 7.3.1 20180323 [gcc-7-branch revision 258812]
    and support for:
    filesurf mailserver pocsagserver servif radioif
    mdpw serial guest ax25k autofwd runutils
    macro yapp filefwd telnetfwd didadit userLT
    fwd-edit rej-edit conv-edit extract fbbcheckmode
    users4convert fts oldmailimport linuxsystemuser
    UptimeConnection closed by foreign host.

The following is the trace result of the other session.

    (gdb) run ./bcm
    Starting program: /bcm/bcm ./bcm
    ...
    OpenBCM V9f93-dirty (Linux)(c) GNU GPL 1992-2013 F. Radlherr, DL8MBT et al.
    OpenBCM is maintained by Markus Baumann, DH8YMB
    ...
    25.08.18 17:06:25l JH4XSY: #R JH4XSY: v
    
    Program received signal SIGSEGV, Segmentation fault.
    0xf738d966 in __strchr_sse2_bsf () from /lib/libc.so.6
    (gdb) where
    #0 0xf738d966 in __strchr_sse2_bsf () from /lib/libc.so.6
    #1 0x080543af in cpuinfo () at ad_linux.cpp:550
    #2 0x08098479 in putversion () at main.cpp:387
    #3 0x0809a1e0 in mailbef (befline=0xa06b810 "v", echo=0) at main.cpp:1375
    #4 0x0808b196 in httpd::start_http (this=0xa06b968, name=0xa052f60 "192.168.0.253") at http.cpp:1511
    #5 0x0808be62 in mblogin_http (name=0xa052f60 "192.168.0.253") at http.cpp:1778
    #6 0x080c6cde in start_newprocess () at task.cpp:677
    #7 0x080c6d63 in newprocess () at task.cpp:699
    #8 0x080c7447 in maintask () at task.cpp:990
    #9 0x080d6aaf in main (argc=2, argv=0xffb84424) at vidinit.cpp:263

I'm using git cloned bcm on openSUSE leap 15.

**Comment by oe5hpm** [comment]
Hi hiroshi,

great to see that also in japan the openbcm is used.
Thanks also for your report in that good qualitiy. With your appended callstack i suspect that the bug was introduced with:

https://github.com/oe5hpm/openBCM/commit/fd1ca4c330d02fe70d694ad18e5fb56e2e44c261

can you provide me the ouput of:
cat /proc/version

i also started a download of the suse image for reproducing that here locally.

best 73,
hannes

**Comment by oe5hpm** [comment]
please provide also /proc/cpuinfo

**Comment by jh4xsy** [comment]
Hi hannes-san

Here is my output: /proc/version is 180 bytes.

    % cat /proc/version 
    Linux version 4.12.14-lp150.12.16-default (geeko@buildhost) (gcc version 7.3.1 20180323 [gcc-7-branch revision 258812] (SUSE Linux) ) #1 SMP Tue Aug 14 17:51:27 UTC 2018 (28574e6)

/proc/cpuinfo is 4264 bytes.

    % cat /proc/cpuinfo
    processor	: 0
    vendor_id	: GenuineIntel
    cpu family	: 6
    model		: 58
    model name	: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
    stepping	: 9
    microcode	: 0x20
    cpu MHz		: 3192.692
    cache size	: 6144 KB
    physical id	: 0
    siblings	: 4
    core id		: 0
    cpu cores	: 4
    apicid		: 0
    initial apicid	: 0
    fpu		: yes
    fpu_exception	: yes
    cpuid level	: 13
    wp		: yes
    flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d
    bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
    bogomips	: 6385.38
    clflush size	: 64
    cache_alignment	: 64
    address sizes	: 36 bits physical, 48 bits virtual
    power management:
    
    processor	: 1
    (snip)

73's
hiroshi

**Comment by oe5hpm** [comment]
hi hiroshi,
many thanks again for the report and help to debug it.

I have reproduced the issue on a opensuse system in a virtual box.
Also i've alredy fixed this on the master branch.

So please pull latest changes and run ... 

btw. i saw that you made several changes within your fork, maybe we have a chance for merging the japanese additions to the mainline source here? what do you mean?

best 73,
hannes

**Comment by jh4xsy** [comment]
Thanks, hannes.
It works.

73's
hiroshi

ps. Japanese addition will be another topics.
